apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  NEXT_HOST: {{ .Values.config.NEXT_HOST }}
  NEXT_PORT: {{ .Values.config.NEXT_PORT }}
