apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      client: {{ .Values.name }}
  template:
    metadata:
      labels:
        client: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: NEXT_HOST
          valueFrom:
            configMapKeyRef:
              key: NEXT_HOST
              name: {{ .Values.name }}-config
        - name: NEXT_PORT
          valueFrom:
            configMapKeyRef:
              key: NEXT_PORT
              name: {{ .Values.name }}-config
